services:
  - type: web
    name: glutenguard
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: glutenguard-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.10.2"
